### ISSUE TITLE
代码中缺少'./share.js'

### ISSUE THREAD

**Issue by Davidyanlong** [cdhuangyong/heatmap3d#1]
您的代码写的很好，发现代码中 `import matrix_set from './share.js'`引入这个文件，但代码中没有找到？您能补充完整吗？

**Comment by cdhuangyong** [comment]
可能漏掉了这个文件，我会尽快补上，感谢使用！多提提意见😁
------&nbsp;原始邮件&nbsp;------
发件人:&quot;yanlong.yang&quot;<notifications@github.com&gt;;
发送时间:2020年7月24日(星期五)&nbsp;中午1:59
收件人:&quot;cdhuangyong/heatmap3d&quot;<heatmap3d@noreply.github.com&gt;;
抄送人:&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:[cdhuangyong/heatmap3d]&nbsp;代码中缺少&#39;./share.js&#39;&nbsp;(#1)



 
您的代码写的很好，发现代码中 import matrix_set from './share.js'引入这个文件，但代码中没有找到？您能补充完整吗？
 
&mdash;

**Comment by cdhuangyong** [comment]
> 您的代码写的很好，发现代码中 `import matrix_set from './share.js'`引入这个文件，但代码中没有找到？您能补充完整吗？

**Comment by cdhuangyong** [comment]
> 您的代码写的很好，发现代码中 `import matrix_set from './share.js'`引入这个文件，但代码中没有找到？您能补充完整吗？

已经上传了

**Comment by Davidyanlong** [comment]
感谢你及时回复，可以加你的QQ或者微信号码？进一步向你请教

**Comment by cdhuangyong** [comment]
465042639😁
------&nbsp;原始邮件&nbsp;------
发件人:&quot;yanlong.yang&quot;<notifications@github.com&gt;;
发送时间:2020年7月24日(星期五)&nbsp;晚上8:13
收件人:&quot;cdhuangyong/heatmap3d&quot;<heatmap3d@noreply.github.com&gt;;
抄送人:&quot;huangyong&quot;<465042639@qq.com&gt;;&quot;State&nbsp;change&quot;<state_change@noreply.github.com&gt;;
主题:Re:&nbsp;[cdhuangyong/heatmap3d]&nbsp;代码中缺少&#39;./share.js&#39;&nbsp;(#1)



 
感谢你及时回复，可以加你的QQ或者微信号码？进一步向你请教
 
&mdash;
